### PR TITLE
Add support for "Ask why a user think an article-reply is useless"

### LINKED ISSUE #97: Ask why a user think an article-reply is useless
If an user clicks "X", display a [`prompt`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) for the user to input reason.

API: https://github.com/cofacts/rumors-api/issues/75

### PR DESCRIPTION
**Pull request by jihchi**
Fixes #97 . 

Most straightforward and naive implementation.

Preview:
screenshot

### CODE REVIEW

**Comment by MrOrz** [comment]
Oops, please run `npm run lint:fix` to fix styles, thanks

**Comment by jihchi** [comment]
Done

**Comment by jihchi** [comment]
It's weird, IT WORKS ON MY MACHINE.

screenshot_2019-03-29 07-48-24

**Comment by MrOrz** [comment]
Thanks a million!

**Pull request merged**
