### PR TITLE
fix: #417 landing page avatar displaying bug

### PR DESCRIPTION
**Pull request by ulayab**

### CODE REVIEW

**Review by MrOrz — APPROVED** [review]
Thanks a lot for finding the missing data!

I think it would be great if we can do the following to [achieve fragment colocation](https://www.apollographql.com/docs/react/data/fragments/#colocating-fragments):
1. move `USER_QUERY` to within `LandingPage/Header`
2. use [`Avatar.fragment.AvatarData`](https://github.com/cofacts/rumors-site/blob/9bece90df7d61e8fa298f3b3e99868e56bec698f/lib/useCurrentUser.js#L13) in query in the component that really uses `Avatar` component (that is `LandingPage/Header`)

@ulayab are you interested in changing the code above? I can do it after merge as well.

**Comment by ulayab** [comment]
Sure! I'll try to deal with it.

**Comment by ulayab** [comment]
Hi @MrOrz  I just update the branch.
BTW, it's my first time using Apollo, so I'm not really sure if it's an expected practice.🤧 
Please advise as necessary, thank you!

**Review by MrOrz — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
