### PR TITLE
add github like contribution graph css and ceil for 1,2 report count

### PR DESCRIPTION
**Pull request by kelvin2go**
https://github.com/cofacts/rumors-site/issues/413

- math.ceil for 1,2 
- add github contribution graph like css 

screen-capture (1)

### CODE REVIEW

**Comment by kelvin2go** [comment]
```
adaptive max contribution
max(10, max(user_contribution)) 作為 contribution graph 的 max scale
```
for this, should it changes max scale to 10 ? 

https://github.com/cofacts/rumors-site/pull/453/files#diff-b170cff4fb01eac4d00fe240d828301e6e8900a7ae3443ad833eeff2a6d64d8fR13


and for test part should i update the story snapshot  after implement?

**Comment by MrOrz** [comment]
Sorry for the late reply, and thanks for taking this issue!

- Current coloring of attribution is fixed at 5 contributions per level `SCALING_FACTOR`. Therefore, daily contribution must exceed 23 (`23 / SCALING_FACTOR = 4.6 ~= 5`) to be painted to deepest color.
- The *adaptive max contribution proposal* wants that max scale to adapt to each user. For example, if the max contribution count of the user is 16 for the past 365 days, we should color the contribution 13~16 with deepest color, and so on.
- However, if the max contribution count of the user for the past 365 days is lower than 10, it would be a bit unfair for other contributors if we also paint those contribution as deepest color. Therefore, in the proposal we added a max-contribution lower-bound: if the max contribution count of the user for the past 365 days is lower than 10, we will use 10 when calculating the color scale.

If we put it in code,
- `MAX_SCALE` remains 4, as available `colorCofactsN` still ranges from `colorCofacts0` to `colorCofacts4`.
- `SCALING_FACTOR` (number of contributions needed to go to the deeper color) should no longer be a constant across different users. If max contribution in `data` is below 10, the scaling factor is `10/MAX_SCALE = 2.5`; otherwise, it is `max contribution / MAX_SCALE`

**Comment by nonumpa** [comment]
@kelvin2go It seems that your local material-ui version is different from this project.

You can try the command writing in [README.md](https://github.com/cofacts/rumors-site#storybook)

```
# install same npm package as this project
npm install

# run test and update snapshot
npm test -- -u
```

**Comment by nonumpa** [comment]
It's abnormal, and I guess other .storyshot files also change `className="makeStyles-tooltipText-311"` to `className="makeStyles-tooltipText-74"`.

Maybe you can google the keyword "npm local vs global package" to solve this problem.

---
Explanation of why I guess your local material-ui version is different from this project and why it should not have `className="makeStyles-tooltipText-*"` change :

First, we take a look at the .storyshot change
snapshot

And then look what [CI test](https://github.com/cofacts/rumors-site/runs/3903371438) result says
> line 35 and 36 means
> It should be `aria-hidden="true"` not `aria-hidden={true}`

> line 48 and 49 means 
> It should be `className="makeStyles-tooltipText-311"` not `className="makeStyles-tooltipText-74"`

That means only `className="makeStyles-colorCofacts*"` is the right change.
This makes sense because you only change the function `scaleColor` which only affects `colorCofacts*`.

**Comment by MrOrz** [comment]
No worries, I think I can make a commit that tries to fix CI

**Comment by kelvin2go** [comment]
hi @MrOrz ,
after test with @nonumpa  
look like   "@material-ui/core": "^4.9.7", 

4.9.9 can pass the test.

not sure, which version is CI using @@'

**Pull request merged**
